const contentDatabase = [
  {
    id: "1",
    src: "images/1.jpg",
    title: "이미지1",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "2",
    src: "videos/1.mp4",
    title: "영상1",
    type: "Video",
    size: "30MB",
    time: "09:56",
  },
  {
    id: "3",
    src: "images/2.jpg",
    title: "이미지3",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "4",
    src: "images/3.jpg",
    title: "이미지4",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "5",
    src: "videos/3.mp4",
    title: "영상2",
    type: "Video",
    size: "30MB",
    time: "14:47",
  },
  {
    id: "6",
    src: "images/2.jpg",
    title: "이미지6",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "7",
    src: "images/3.jpg",
    title: "이미지7",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "13",
    src: "images/1.jpg",
    title: "이미지8",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "9",
    src: "images/1.jpg",
    title: "이미지9",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "10",
    src: "images/2.jpg",
    title: "이미지10",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "11",
    src: "images/3.jpg",
    title: "이미지11",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "12",
    src: "images/1.jpg",
    title: "이미지12",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "8",
    src: "videos/3.mp4",
    title: "영상3",
    type: "Video",
    size: "30MB",
    time: "12:14",
  },
  {
    id: "14",
    src: "images/2.jpg",
    title: "이미지14",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "15",
    src: "images/1.jpg",
    title: "이미지15",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "16",
    src: "images/2.jpg",
    title: "이미지16",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "17",
    src: "images/3.jpg",
    title: "이미지17",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "18",
    src: "images/1.jpg",
    title: "이미지18",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "19",
    src: "images/2.jpg",
    title: "이미지19",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "20",
    src: "images/3.jpg",
    title: "이미지20",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "21",
    src: "images/1.jpg",
    title: "이미지21",
    type: "Image",
    size: "30MB",
    time: "None",
  },
  {
    id: "22",
    src: "images/2.jpg",
    title: "이미지22",
    type: "Image",
    size: "30MB",
    time: "None",
  },
];

export default contentDatabase;
